version: '3.7'
services:
  mysqldb:
    image: mysql:8
    ports:
      - '3306:3306'
    volumes:
      - ./init_db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=app
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=pass
